import type { Config } from "tailwindcss";

// Cyber-Financial Matrix design system (Stitch redesign).
// Dark-mode-first, neon-accented command-center aesthetic.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#00e297",
        "surface-bright": "#393939",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#9900d0",
        "secondary-fixed": "#4dffb2",
        "surface-tint": "#00dbe9",
        "inverse-on-surface": "#313030",
        error: "#ffb4ab",
        "primary-fixed-dim": "#00dbe9",
        "surface-variant": "#353534",
        "surface-dim": "#131313",
        "on-surface-variant": "#b9cacb",
        "on-primary-fixed": "#002022",
        "surface-container-lowest": "#0e0e0e",
        secondary: "#f4fff5",
        "on-secondary": "#003822",
        primary: "#dbfcff",
        background: "#131313",
        "on-tertiary-fixed": "#320047",
        "on-primary-fixed-variant": "#004f54",
        "on-primary": "#00363a",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-tertiary": "#520071",
        surface: "#131313",
        "on-secondary-fixed-variant": "#005234",
        "tertiary-fixed": "#f8d8ff",
        "on-secondary-fixed": "#002112",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#00ffab",
        "outline-variant": "#3b494b",
        "on-tertiary-fixed-variant": "#74009f",
        tertiary: "#fff2fd",
        "error-container": "#93000a",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        "on-background": "#e5e2e1",
        "tertiary-container": "#f4ccff",
        "tertiary-fixed-dim": "#ecb2ff",
        "surface-container-highest": "#353534",
        "on-secondary-container": "#007149",
        "primary-container": "#00f0ff",
        "primary-fixed": "#7df4ff",
        "surface-container-low": "#1c1b1b",
        outline: "#849495",
        "surface-container": "#201f1f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-md": ["Hanken Grotesk", "ui-sans-serif", "sans-serif"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-lg": ["Hanken Grotesk", "ui-sans-serif", "sans-serif"],
        "mono-data": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-md": ["Hanken Grotesk", "ui-sans-serif", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
